"""Read-only triage of the B1 catch-all class into three evidence-backed tiers.

Why this exists: `_gen_drift_inventory.py:classify()` ends in `return B1`, so B1 is the
complement of A/B2/C/D/E — not a proven "irreproducible original work" set. Codex raised
this in peer-chat 2026-07-28T13:48:04+09:00. Committing B1 wholesale would freeze that
misclassification into a retention decision.

This script writes nothing but its own two outputs (a manifest + a digest). It does not
commit, delete, stage, or move anything, and it does not claim any tier "should" be
deleted. Tier assignment is a mechanical function of recorded signals; the reason string
for every file names the signal that put it there, so each row can be argued with.

Re-run: python proposals/uncommitted-drift-inventory-v0.1/triage_b1.py
"""
import datetime
import hashlib
import importlib.util
import json
import os
import re
import subprocess
import sys

ROOT = "D:/WeilanSkillEvolution"
OUT_DIR = os.path.join(ROOT, "proposals/uncommitted-drift-inventory-v0.1")
GEN = os.path.join(ROOT, "proposals/bounded-scheduler-v0.1/impl/_gen_drift_inventory.py")

# Self-exclusion: this script and its own outputs are created by the episode that writes
# the triage, so counting them would let the manifest inflate its own subject matter.
SELF = {"triage_b1.py", "B1_TRIAGE.tsv", "B1_TRIAGE.json"}

LEDGER_BASENAMES = {
    "peer-chat.jsonl", "codex-inbox.jsonl", "codex-inbox-replies.jsonl",
    "concurrent-receipts.jsonl", "blocker-quarantine.jsonl", "owner-inbox.jsonl",
    "owner-inbox-replies.jsonl", "owner-inbox-processed.jsonl",
}

# One-shot helper naming convention, applied *directory-independently* — that is the whole
# correction. The A rule in the generator only fires under two directories, which is why
# 45 `_append_*`/`_msg_*`/`_close_*` files under charter-daily-push-v0.1/ fell through to B1.
ONESHOT_NAME = re.compile(
    r"^_(append|msg|close|open|gen|emit|post|reply|send|write|gen)[_.-]", re.I)
# Broader: any leading-underscore helper that is not a python package marker.
UNDERSCORE_HELPER = re.compile(r"^_(?!_init__)")
SCRATCH_NAME = re.compile(r"(\.tmp$|~$|\.bak$|^wf-\d{8}-)", re.I)
DERIVED_MARKER = re.compile(
    r"(auto[- ]?generated|autogenerated|generated by|do not edit|复跑即可再生|本文件由.{0,12}生成)", re.I)


def git(args, **kw):
    return subprocess.run(["git"] + args, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", cwd=ROOT, **kw).stdout


def load_classifier():
    """Reuse the *exact* classifier that produced the B1 figure, so this is a same-yardstick split."""
    spec = importlib.util.spec_from_file_location("_gen_drift_inventory", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def collect_b1(mod):
    recs = []
    for line in git(["status", "--porcelain", "-uall"]).splitlines():
        st, p = line[:2].strip(), line[3:].strip().strip('"')
        base = os.path.basename(p)
        if base in SELF or base in mod.SELF:
            continue
        if mod.classify(p) != "B1":
            continue
        fp = os.path.join(ROOT, p)
        if not os.path.isfile(fp):
            continue
        data = open(fp, "rb").read()
        recs.append(dict(
            status=st, path=p, base=base, size=len(data),
            sha256=hashlib.sha256(data).hexdigest(),
            blob=hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest(),
            mtime=datetime.datetime.fromtimestamp(os.path.getmtime(fp)).isoformat(timespec="minutes"),
            head=data[:4096].decode("utf-8", "replace"),
        ))
    return recs


def name_uniqueness():
    """A basename shared by several repo paths cannot carry attribution: a ledger line saying
    "FINDING.md" does not name *this* FINDING.md. Distinctiveness is what makes name-level
    evidence admissible, and the generator's basename test silently skipped this check."""
    counts = {}
    paths = [l for l in git(["ls-files"]).splitlines() if l]
    paths += [l[3:].strip().strip('"') for l in git(["status", "--porcelain", "-uall"]).splitlines()]
    for p in paths:
        counts[os.path.basename(p)] = counts.get(os.path.basename(p), 0) + 1
    return counts


def ledger_mentions(recs, uniq):
    """Provenance from the append-only ledgers, split into path-level (attributable) and
    name-level (attributable only when the basename is unique repo-wide)."""
    corpus = {}
    impl = os.path.join(ROOT, "proposals/bounded-scheduler-v0.1/impl")
    for fn in LEDGER_BASENAMES:
        fp = os.path.join(impl, fn)
        if os.path.isfile(fp):
            corpus[fn] = open(fp, encoding="utf-8", errors="replace").read()
    for r in recs:
        variants = [r["path"], r["path"].replace("/", "\\\\"), r["path"].replace("/", "\\")]
        r["ledger_path_hits"] = {fn: c for fn, txt in corpus.items()
                                 if (c := sum(txt.count(v) for v in variants))}
        r["ledger_name_hits"] = {fn: c for fn, txt in corpus.items()
                                 if (c := txt.count(r["base"]))}
        r["ledger_path_total"] = sum(r["ledger_path_hits"].values())
        r["ledger_total"] = sum(r["ledger_name_hits"].values())
        r["name_unique"] = uniq.get(r["base"], 0) <= 1
        # Recorded, never promoting: the proposal directory being discussed says the *line of
        # work* is real, not that this particular file is the artifact anyone depended on.
        # It is here so a human adjudicating T3 has the next lead already measured.
        seg = r["path"].split("/")
        r["dir_token"] = seg[1] if len(seg) > 2 and seg[0] == "proposals" else seg[0]
        r["dir_ledger_hits"] = sum(txt.count(r["dir_token"]) for txt in corpus.values())


ENUM_ABS = 20      # cites this many distinct candidates …
ENUM_RATIO = 0.25  # … or this share of them → treat as an enumerating snapshot, not a citation


def tracked_refs(recs):
    """Committed files that reference this artifact — the strongest durability signal, since
    history already depends on it. Two separate greps: the full repo-relative path (always
    attributable) and the bare basename (attributable only for repo-unique names).

    One correction learned the hard way: a tracked file that enumerates the whole worktree
    (witness snapshots, inventories, accounting tables) "cites" every path trivially. Counting
    those would manufacture provenance for anything that merely existed when the snapshot ran.
    Such citers are detected by measured breadth and excluded, and the exclusion is reported."""
    for r in recs:
        r["tracked_path_refs"], r["tracked_name_refs"] = [], []
    by_key = {}
    for r in recs:
        by_key.setdefault(r["path"], []).append(("path", r))
        by_key.setdefault(r["base"], []).append(("name", r))
    keys = sorted(by_key)
    CHUNK = 40
    for i in range(0, len(keys), CHUNK):
        args = ["grep", "--cached", "-F", "-I", "-o", "--no-color"]
        for k in keys[i:i + CHUNK]:
            args += ["-e", k]
        for line in git(args).splitlines():
            if ":" not in line:
                continue
            path, match = line.split(":", 1)
            if os.path.basename(path) in LEDGER_BASENAMES or os.path.basename(path) in SELF:
                continue
            for kind, r in by_key.get(match.strip(), []):
                bucket = r["tracked_path_refs"] if kind == "path" else r["tracked_name_refs"]
                if path != r["path"] and path not in bucket:
                    bucket.append(path)

    breadth = {}
    for r in recs:
        for p in set(r["tracked_path_refs"]) | set(r["tracked_name_refs"]):
            breadth[p] = breadth.get(p, 0) + 1
    enumerators = {p: n for p, n in breadth.items()
                   if n >= ENUM_ABS or n >= ENUM_RATIO * max(1, len(recs))}
    for r in recs:
        r["enumerating_refs"] = sorted(p for p in
                                       set(r["tracked_path_refs"]) | set(r["tracked_name_refs"])
                                       if p in enumerators)
        r["tracked_path_refs"] = [p for p in r["tracked_path_refs"] if p not in enumerators]
        r["tracked_name_refs"] = [p for p in r["tracked_name_refs"] if p not in enumerators]
    return sorted(enumerators.items(), key=lambda kv: -kv[1])


def reachable_blobs():
    """Blob oids reachable from any ref. Present-and-reachable means `git clean -fd` cannot
    destroy the bytes — it does NOT mean the path is in commit history, nor that the holding
    ref travels with a clone (refs/codex/** does not)."""
    out = set()
    for line in git(["rev-list", "--all", "--objects"]).splitlines():
        if line:
            out.add(line.split(" ", 1)[0])
    return out


def assign(r):
    """Return (tier, reason). Tiers are Codex's three, 2026-07-28T13:48:04+09:00."""
    base, head = r["base"], r["head"]
    if SCRATCH_NAME.search(base):
        return "T2", f"scratch/temp filename shape ({base})"
    if ONESHOT_NAME.match(base):
        return "T2", f"one-shot helper naming convention `_{ONESHOT_NAME.match(base).group(1)}_*` (directory-independent)"
    if UNDERSCORE_HELPER.match(base):
        # Extension-independent: `_scan_out.json` is as episode-local as `_scan.py`, and a
        # ledger citing it once does not make it durable.
        return "T2", f"leading-underscore episode-local helper ({os.path.splitext(base)[1] or 'no ext'})"
    if DERIVED_MARKER.search(head):
        return "T2", "file declares itself generated/derived in its first 4KB"
    if r["tracked_path_refs"]:
        n = len(r["tracked_path_refs"])
        return "T1", f"{n} tracked file(s) cite this full path, e.g. {r['tracked_path_refs'][0]}"
    if r["ledger_path_total"] > 0:
        hits = ",".join(f"{k.split('.')[0]}x{v}" for k, v in sorted(r["ledger_path_hits"].items()))
        return "T1", f"full path cited in append-only ledgers ({hits})"
    if r["name_unique"] and r["tracked_name_refs"]:
        return "T1", (f"repo-unique basename cited by {len(r['tracked_name_refs'])} tracked file(s), "
                      f"e.g. {r['tracked_name_refs'][0]}")
    if r["name_unique"] and r["ledger_total"] > 0:
        hits = ",".join(f"{k.split('.')[0]}x{v}" for k, v in sorted(r["ledger_name_hits"].items()))
        return "T1", f"repo-unique basename named in append-only ledgers ({hits})"
    if not r["name_unique"] and (r["tracked_name_refs"] or r["ledger_total"]):
        return "T3", ("only ambiguous basename hits — this name is shared by "
                      f"{r['name_dupes']} repo paths, so the citation does not attribute to this file")
    return "T3", "no path citation and no attributable name hit — provenance unknown, not adjudicated"


SECRET_PATTERNS = None


def load_secret_patterns():
    """Reuse the push scanner's patterns rather than inventing a second, weaker set."""
    global SECRET_PATTERNS
    p = os.path.join(ROOT, "proposals/charter-daily-push-v0.1/scan_push_manifest.py")
    spec = importlib.util.spec_from_file_location("scan_push_manifest", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    SECRET_PATTERNS = mod.PATTERNS
    return mod.PATTERNS


def scan_secrets(recs):
    """PATTERNS are byte-regexes, so scan raw bytes — decoding first would let an
    undecodable byte silently drop a match."""
    pats = load_secret_patterns()
    for r in recs:
        with open(os.path.join(ROOT, r["path"]), "rb") as fh:
            data = fh.read()
        r["secret_hits"] = [name for name, rx in pats if rx.search(data)]


def main():
    mod = load_classifier()
    recs = collect_b1(mod)
    uniq = name_uniqueness()
    ledger_mentions(recs, uniq)
    for r in recs:
        r["name_dupes"] = uniq.get(r["base"], 0)
    enumerators = tracked_refs(recs)
    reach = reachable_blobs()
    for r in recs:
        r["bytes_reachable_from_ref"] = r["blob"] in reach
        r["tier"], r["reason"] = assign(r)
    scan_secrets(recs)
    recs.sort(key=lambda r: (r["tier"], r["path"]))

    # Digest covers only content-identity + verdict, never mtime or counts that drift.
    canon = "\n".join(f"{r['tier']}\t{r['path']}\t{r['size']}\t{r['sha256']}" for r in recs)
    digest = hashlib.sha256(canon.encode()).hexdigest()

    head = git(["rev-parse", "HEAD"]).strip()
    tsv = ["tier\tstatus\tsize\tsha256_12\treachable\tsecret_hits\tpath\treason"]
    for r in recs:
        tsv.append("\t".join([
            r["tier"], r["status"], str(r["size"]), r["sha256"][:12],
            "yes" if r["bytes_reachable_from_ref"] else "no",
            ",".join(r["secret_hits"]) or "-", r["path"], r["reason"]]))
    open(os.path.join(OUT_DIR, "B1_TRIAGE.tsv"), "w", encoding="utf-8", newline="\n").write(
        "\n".join(tsv) + "\n")

    payload = dict(
        authority="none",
        purpose="split the B1 catch-all into three tiers with per-file retain reasons; "
                "no tier assignment authorizes commit or deletion",
        generated_at=datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
        git_head=head,
        classifier_source="proposals/bounded-scheduler-v0.1/impl/_gen_drift_inventory.py::classify",
        manifest_digest=digest,
        tier_definitions=dict(
            T1="has provenance and may need durability: a tracked file or an append-only "
               "ledger names it. Candidate for the first cut, per-file reason required.",
            T2="generated or one-shot: episode-local helper naming convention, scratch name, "
               "or self-declared derived. NOT proposed for commit — and NOT proposed for "
               "deletion either; untracked != should-delete.",
            T3="provenance unknown: no ledger mention, no tracked reference. Explicitly "
               "withheld from any cut until adjudicated; a catch-all label must not "
               "silently conscript these the way B1 did.",
        ),
        excluded_enumerating_citers=[
            dict(path=p, cites_candidates=n) for p, n in enumerators],
        enumerator_rule=f"a tracked citer naming >= {ENUM_ABS} candidates, or >= "
                        f"{ENUM_RATIO:.0%} of them, is an inventory/snapshot rather than a "
                        f"dependency and does not confer provenance",
        counts={t: sum(1 for r in recs if r["tier"] == t) for t in ("T1", "T2", "T3")},
        bytes={t: sum(r["size"] for r in recs if r["tier"] == t) for t in ("T1", "T2", "T3")},
        files=[{k: r[k] for k in (
            "tier", "reason", "status", "path", "size", "sha256", "mtime",
            "name_unique", "name_dupes", "ledger_path_total", "ledger_total",
            "dir_token", "dir_ledger_hits",
            "tracked_path_refs", "tracked_name_refs", "enumerating_refs",
            "bytes_reachable_from_ref", "secret_hits")}
            for r in recs],
    )
    open(os.path.join(OUT_DIR, "B1_TRIAGE.json"), "w", encoding="utf-8", newline="\n").write(
        json.dumps(payload, ensure_ascii=False, indent=1) + "\n")

    print("B1 total:", len(recs), "bytes", sum(r["size"] for r in recs))
    for t in ("T1", "T2", "T3"):
        g = [r for r in recs if r["tier"] == t]
        print(f"  {t}: {len(g)} files / {sum(r['size'] for r in g):,} bytes")
    print("manifest_digest:", digest)
    print("secret hits:", sum(1 for r in recs if r["secret_hits"]))
    print("HEAD:", head)


if __name__ == "__main__":
    sys.exit(main())
